# Generated by Django 4.2.30 on 2026-09-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='category',
            field=models.CharField(choices=[('character', 'Character'), ('weapon', 'Weapon'), ('location', 'Location')], max_length=20),
        ),
    ]
