# Generated by Django 4.2.30 on 2026-09-12 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0003_wikientry_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
