# Generated by Django 4.2.30 on 2026-09-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_wikientry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
