# Generated by Django 4.2.30 on 2026-09-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_wikientry_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikientry',
            name='image_url',
        ),
        migrations.AddField(
            model_name='wikientry',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
