# Generated by Django 4.2.30 on 2026-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_remove_wikientry_image_url_wikientry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='wikientry',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
