# Generated by Django 4.2.30 on 2026-09-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_wikientry_content_alter_wikientry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wiki_images/'),
        ),
    ]
