# Generated by Django 4.2.30 on 2026-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_alter_wikientry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
