# Generated by Django 4.2.30 on 2026-09-17 11:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_alter_wikientry_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
